spring:
  application:
    name: api-gateway

server:
  port: 3001

# 配置服务注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/

zuul:
  routes:
    eureka-client: /eureka-client/**
    web-service: /web-service/**